---
title: "Plotly"
---

This is the page shows some example plotly plots.

```{r}
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
```


Get the data I care about..

```{r}
set.seed(1)

data(nyc_airbnb)
nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2) %>%
  select(boro = neighbourhood_group, neighbourhood, rating, price, room_type,
         latitude, longitude) %>%
  filter(!is.na(rating), 
         boro == "Manhattan",
         room_type == "Entire home/apt",
         price %in% 100:500)  %>% 
  sample_n(5000) # make the sample from only 5000 rows
```

### Plotly scatterplot

```{r}
# ?plot_ly
nyc_airbnb %>%
  plot_ly(x = ~longitude, y = ~latitude, type = "scatter", mode = "markers",
          alpha = 0.5, 
          color = ~price)
# the mapping text is only the (longitude, latitude)
```


```{r}
nyc_airbnb %>%
  # /n means a new line
  mutate(text_label = str_c("Price: $", price, '\nRating: ', rating)) %>% 
  plot_ly(x = ~longitude, y = ~latitude, type = "scatter", mode = "markers",
          alpha = 0.5, 
          color = ~price,
          # mapping the varable "text_lable" in the text
          text = ~text_label)
```

### Plotly boxplot

```{r}
nyc_airbnb %>% 
   plot_ly(y = ~price, color = ~neighbourhood, type = "box")
```



```{r}
common_neighborhoods =
  nyc_airbnb %>% 
  # order the count
  count(neighbourhood, sort = TRUE) %>% 
  top_n(8) %>% 
  # Selecting by n
  select(neighbourhood)


inner_join(nyc_airbnb, common_neighborhoods,
             by = "neighbourhood") %>% 
  # order according to median of price
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(y = ~price, color = ~neighbourhood, type = "box",
          colors = "Set2")
```


### Bar plots

Trust me, you can make these. See?

```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar")
```



### ggplotly

```{r}
# help the save the advantage of ggplot, and do something else using ggplotly
scatter_ggplot = 
  nyc_airbnb %>%
  ggplot(aes(x = longitude, y = latitude, color = price)) +
  geom_point(alpha = 0.25) +
  scale_color_viridis() +
  coord_cartesian() +
  theme_classic()

ggplotly(scatter_ggplot)
```


